In [1]:
import pandas as pd

In [2]:
dataset= pd.read_csv('insurance_pre.csv')

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset=pd.get_dummies(dataset)

In [5]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_female', 'sex_male',
       'smoker_no', 'smoker_yes'],
      dtype='object')

In [6]:
independent=dataset[['age', 'bmi', 'children','sex_female', 'sex_male','smoker_no', 'smoker_yes']]
independent

      age     bmi  children  sex_female  sex_male  smoker_no  smoker_yes
0      19  27.900         0           1         0          0           1
1      18  33.770         1           0         1          1           0
2      28  33.000         3           0         1          1           0
3      33  22.705         0           0         1          1           0
4      32  28.880         0           0         1          1           0
...   ...     ...       ...         ...       ...        ...         ...
1333   50  30.970         3           0         1          1           0
1334   18  31.920         0           1         0          1           0
1335   18  36.850         0           1         0          1           0
1336   21  25.800         0           1         0          1           0
1337   61  29.070         0           1         0          0           1

[1338 rows x 7 columns]

In [7]:
dependent=dataset[['charges']]
dependent

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [8]:
# from sklearn.model_selection import train_test_split
# x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.30,random_state=0)

In [10]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import AdaBoostRegressor
param_grid={'n_estimators':[50,100,150,200,250,300,350,400,450,500],'loss':['linear','square','exponential'],'random_state':[None]}
grid= GridSearchCV(AdaBoostRegressor(),param_grid,refit=True,verbose=3,n_jobs=-1)   
grid.fit(independent,dependent)

Fitting 5 folds for each of 30 candidates, totalling 150 fits

C:\Users\Jayarajan\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GridSearchCV(estimator=AdaBoostRegressor(), n_jobs=-1,
             param_grid={'loss': ['linear', 'square', 'exponential'],
                         'n_estimators': [50, 100, 150, 200, 250, 300, 350, 400,
                                          450, 500],
                         'random_state': [None]},
             verbose=3)

In [11]:
re=grid.cv_results_

In [12]:
print("The R_score value for the best parameter{}:".format(grid.best_params_))

The R_score value for the best parameter{'loss': 'linear', 'n_estimators': 300, 'random_state': None}:

In [13]:
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_loss,param_n_estimators,param_random_state,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.055169,0.012377,0.009597,0.002151,linear,50,None,"{'loss': 'linear', 'n_estimators': 50, 'random...",0.851398,0.782322,0.849729,0.808838,0.847997,0.828057,0.027832,2
1,0.055768,0.006964,0.007993,0.001415,linear,100,None,"{'loss': 'linear', 'n_estimators': 100, 'rando...",0.841489,0.769068,0.810290,0.807641,0.831981,0.812094,0.025036,8
2,0.054769,0.018070,0.009800,0.001940,linear,150,None,"{'loss': 'linear', 'n_estimators': 150, 'rando...",0.841655,0.790390,0.760176,0.809357,0.846942,0.809704,0.032353,9
3,0.052172,0.007619,0.010393,0.002724,linear,200,None,"{'loss': 'linear', 'n_estimators': 200, 'rando...",0.837013,0.778297,0.842619,0.818077,0.849658,0.825133,0.025658,3
4,0.073155,0.012554,0.008195,0.002399,linear,250,None,"{'loss': 'linear', 'n_estimators': 250, 'rando...",0.845427,0.775848,0.844454,0.768596,0.835797,0.814024,0.034372,7
5,0.044774,0.006397,0.009596,0.002240,linear,300,None,"{'loss': 'linear', 'n_estimators': 300, 'rando...",0.852573,0.782430,0.854553,0.820208,0.836221,0.829197,0.026483,1
6,0.046971,0.011710,0.008396,0.002415,linear,350,None,"{'loss': 'linear', 'n_estimators': 350, 'rando...",0.825755,0.770737,0.846952,0.817290,0.837226,0.819592,0.026418,5
7,0.054165,0.014233,0.007796,0.001598,linear,400,None,"{'loss': 'linear', 'n_estimators': 400, 'rando...",0.809008,0.764809,0.766278,0.819260,0.847394,0.801350,0.031827,10
8,0.046970,0.007181,0.008396,0.000489,linear,450,None,"{'loss': 'linear', 'n_estimators': 450, 'rando...",0.815966,0.792301,0.855340,0.814168,0.823783,0.820312,0.020397,4
9,0.050371,0.012299,0.008797,0.001720,linear,500,None,"{'loss': 'linear', 'n_estimators': 500, 'rando...",0.849477,0.772654,0.824752,0.817328,0.830300,0.818902,0.025457,6
10,0.176496,0.008035,0.014192,0.001469,square,50,None,"{'loss': 'square', 'n_estimators': 50, 'random...",0.535740,0.423339,0.477525,0.482464,0.489564,0.481726,0.035794,13
11,0.329210,0.007861,0.022388,0.003496,square,100,None,"{'loss': 'square', 'n_estimators': 100, 'rando...",0.502728,0.391483,0.418144,0.473767,0.462665,0.449757,0.039860,17
12,0.499712,0.020355,0.030982,0.003845,square,150,None,"{'loss': 'square', 'n_estimators': 150, 'rando...",0.509290,0.377736,0.404268,0.450698,0.452894,0.438977,0.045233,19
13,0.641827,0.008863,0.040377,0.001853,square,200,None,"{'loss': 'square', 'n_estimators': 200, 'rando...",0.501083,0.368092,0.399905,0.437549,0.438933,0.429112,0.044551,25
14,0.784548,0.016054,0.047173,0.002314,square,250,None,"{'loss': 'square', 'n_estimators': 250, 'rando...",0.485695,0.361966,0.397787,0.438304,0.439382,0.424627,0.041907,29
15,0.927267,0.009820,0.058766,0.004789,square,300,None,"{'loss': 'square', 'n_estimators': 300, 'rando...",0.501997,0.359140,0.404212,0.439600,0.441314,0.429253,0.047089,24
16,1.084776,0.005238,0.061766,0.001165,square,350,None,"{'loss': 'square', 'n_estimators': 350, 'rando...",0.492736,0.373472,0.389167,0.438113,0.442001,0.427098,0.042347,26
17,1.245483,0.016415,0.069960,0.000894,square,400,None,"{'loss': 'square', 'n_estimators': 400, 'rando...",0.503204,0.363888,0.397414,0.434582,0.434914,0.426801,0.046444,27
18,1.314641,0.190816,0.080154,0.013926,square,450,None,"{'loss': 'square', 'n_estimators': 450, 'rando...",0.495648,0.360329,0.395318,0.438822,0.435818,0.425187,0.045525,28
19,1.595678,0.023109,0.087950,0.004896,square,500,None,"{'loss': 'square', 'n_estimators': 500, 'rando...",0.484892,0.364745,0.401371,0.428861,0.434368,0.422847,0.039637,30
20,0.176095,0.004529,0.012993,0.001265,exponential,50,None,"{'loss': 'exponential', 'n_estimators': 50, 'r...",0.615053,0.522821,0.579596,0.588888,0.592130,0.579698,0.030738,11
21,0.340599,0.006521,0.021988,0.002097,exponential,100,None,"{'loss': 'exponential', 'n_estimators': 100, '...",0.567229,0.423730,0.480416,0.522586,0.509672,0.500727,0.047584,12
22,0.512306,0.012933,0.029983,0.002097,exponential,150,None,"{'loss': 'exponential', 'n_estimators': 150, '...",0.538553,0.406825,0.449782,0.493684,0.484942,0.474757,0.044205,14
23,0.669809,0.005914,0.037579,0.001019,exponential,200,None,"{'loss': 'exponential', 'n_estimators': 200, '...",0.531605,0.381325,0.442972,0.467546,0.487904,0.462270,0.049834,15
24,0.827124,0.013973,0.044774,0.001165,exponential,250,None,"{'loss': 'exponential', 'n_estimators': 250, '...",0.517476,0.369484,0.441317,0.451709,0.473378,0.450673,0.048288,16
25,0.977235,0.007193,0.054369,0.000799,exponential,300,None,"{'loss': 'exponential', 'n_estimators': 300, '...",0.514188,0.358257,0.424216,0.442575,0.470339,0.441915,0.051660,18
26,1.124748,0.007223,0.063364,0.001019,exponential,350,None,"{'loss': 'exponential', 'n_estimators': 350, '...",0.506872,0.346670,0.416573,0.440883,0.463226,0.434845,0.053176,21
27,1.293648,0.007933,0.071160,0.001938,exponential,400,None,"{'loss': 'exponential', 'n_estimators': 400, '...",0.503593,0.349685,0.424934,0.438255,0.468542,0.437002,0.051382,20
28,1.440963,0.015216,0.079555,0.001019,exponential,450,None,"{'loss': 'exponential', 'n_estimators': 450, '...",0.507864,0.343680,0.416536,0.432785,0.463423,0.432858,0.054368,23
29,1.513921,0.114275,0.073562,0.017032,exponential,500,None,"{'loss': 'exponential', 'n_estimators': 500, '...",0.514800,0.344625,0.410663,0.433538,0.464961,0.433717,0.056603,22

In [14]:
age_input=int(input("Enter age: "))
bmi_input=float(input("Enter bmi: "))
children_input=float(input("Enter children: "))
gender_male_input=int(input("Enter Gender: "))
gender_female_input=int(input("Enter Gender: "))
smoker_yes_input=int(input("Enter smoker: "))
smoker_no_input=int(input("Enter smoker: "))

Enter age: 20
Enter bmi: 34.5
Enter children: 4
Enter Gender: 1
Enter Gender: 0
Enter smoker: 0
Enter smoker: 1

In [15]:
future_predict=grid.predict([[age_input,bmi_input,children_input,gender_male_input,gender_female_input,smoker_yes_input,smoker_no_input]])
print("Future Prediction{}".format(future_predict))

Future Prediction[38894.02649067]

C:\Users\Jayarajan\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but AdaBoostRegressor was fitted with feature names
  warnings.warn(