In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv('insurance_pre.csv')

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset=pd.get_dummies(dataset)
dataset

,age,bmi,children,charges,sex_female,sex_male,smoker_no,smoker_yes
0,19,27.900,0,16884.92400,1,0,0,1
1,18,33.770,1,1725.55230,0,1,1,0
2,28,33.000,3,4449.46200,0,1,1,0
3,33,22.705,0,21984.47061,0,1,1,0
4,32,28.880,0,3866.85520,0,1,1,0
...,...,...,...,...,...,...,...,...
1333,50,30.970,3,10600.54830,0,1,1,0
1334,18,31.920,0,2205.98080,1,0,1,0
1335,18,36.850,0,1629.83350,1,0,1,0
1336,21,25.800,0,2007.94500,1,0,1,0
1337,61,29.070,0,29141.36030,1,0,0,1

In [5]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_female', 'sex_male',
       'smoker_no', 'smoker_yes'],
      dtype='object')

In [6]:
independent=dataset[['age', 'bmi', 'children','sex_female', 'sex_male','smoker_no', 'smoker_yes']]
independent

      age     bmi  children  sex_female  sex_male  smoker_no  smoker_yes
0      19  27.900         0           1         0          0           1
1      18  33.770         1           0         1          1           0
2      28  33.000         3           0         1          1           0
3      33  22.705         0           0         1          1           0
4      32  28.880         0           0         1          1           0
...   ...     ...       ...         ...       ...        ...         ...
1333   50  30.970         3           0         1          1           0
1334   18  31.920         0           1         0          1           0
1335   18  36.850         0           1         0          1           0
1336   21  25.800         0           1         0          1           0
1337   61  29.070         0           1         0          0           1

[1338 rows x 7 columns]

In [7]:
dependent=dataset[['charges']]
dependent

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [8]:
# from sklearn.model_selection import train_test_split
# x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.30,random_state=0)

In [10]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
param_grid={'criterion':['squared_error','friedman_mse','absolute_error','absolute_error'],'splitter':['best','random'],'max_features':[None,'auto','sqrt','log2']}
grid=GridSearchCV(DecisionTreeRegressor(),param_grid,refit=True,verbose=3,n_jobs=-1)
grid.fit(independent,dependent)

Fitting 5 folds for each of 32 candidates, totalling 160 fits

GridSearchCV(estimator=DecisionTreeRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'friedman_mse',
                                       'absolute_error', 'absolute_error'],
                         'max_features': [None, 'auto', 'sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             verbose=3)

In [11]:
re=grid.cv_results_

In [13]:
print("The Rscore value of the best parameter{}".format(grid.best_params_))

The Rscore value of the best parameter{'criterion': 'absolute_error', 'max_features': 'auto', 'splitter': 'best'}

In [16]:
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.015398,0.002867,0.005193,0.000746,squared_error,None,best,"{'criterion': 'squared_error', 'max_features':...",0.715651,0.614297,0.727299,0.737565,0.667148,0.692392,0.045905,13
1,0.009000,0.001997,0.005596,0.001025,squared_error,None,random,"{'criterion': 'squared_error', 'max_features':...",0.694224,0.576580,0.767526,0.728389,0.731557,0.699655,0.065768,10
2,0.013785,0.002478,0.005200,0.000979,squared_error,auto,best,"{'criterion': 'squared_error', 'max_features':...",0.723882,0.615356,0.733608,0.696290,0.660911,0.686009,0.043422,20
3,0.010392,0.001493,0.006197,0.001165,squared_error,auto,random,"{'criterion': 'squared_error', 'max_features':...",0.712231,0.544194,0.680691,0.728434,0.723642,0.677838,0.068862,23
4,0.012790,0.002918,0.007397,0.002332,squared_error,sqrt,best,"{'criterion': 'squared_error', 'max_features':...",0.714329,0.624765,0.676559,0.654224,0.704031,0.674782,0.032702,25
5,0.011993,0.003686,0.011996,0.005544,squared_error,sqrt,random,"{'criterion': 'squared_error', 'max_features':...",0.687757,0.480660,0.674793,0.712401,0.662441,0.643610,0.083139,29
6,0.010794,0.001600,0.005800,0.001169,squared_error,log2,best,"{'criterion': 'squared_error', 'max_features':...",0.743452,0.612826,0.709979,0.682670,0.696645,0.689114,0.043142,16
7,0.010396,0.002652,0.006395,0.001196,squared_error,log2,random,"{'criterion': 'squared_error', 'max_features':...",0.593533,0.476273,0.656088,0.669153,0.611171,0.601243,0.068404,31
8,0.013389,0.002153,0.006197,0.001599,friedman_mse,None,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.710686,0.653738,0.724798,0.731515,0.685698,0.701287,0.028491,8
9,0.011993,0.002605,0.005400,0.001022,friedman_mse,None,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.683885,0.612005,0.717620,0.680603,0.690315,0.676886,0.034963,24
10,0.012791,0.002314,0.007197,0.001599,friedman_mse,auto,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.716669,0.650370,0.726477,0.733392,0.677296,0.700841,0.031840,9
11,0.010597,0.001350,0.006593,0.001024,friedman_mse,auto,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.760002,0.667671,0.711392,0.714331,0.712762,0.713232,0.029217,3
12,0.010191,0.001940,0.006799,0.002322,friedman_mse,sqrt,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.756215,0.600432,0.675872,0.751100,0.739286,0.704581,0.059507,6
13,0.009993,0.003023,0.005593,0.000489,friedman_mse,sqrt,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.685930,0.646230,0.724716,0.687431,0.661637,0.681189,0.026685,22
14,0.009997,0.001258,0.006994,0.001676,friedman_mse,log2,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.629219,0.584997,0.634642,0.729070,0.737534,0.663092,0.059917,27
15,0.010593,0.002415,0.006397,0.002332,friedman_mse,log2,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.603243,0.564374,0.648681,0.662602,0.510132,0.597806,0.055894,32
16,0.063363,0.002726,0.005597,0.001356,absolute_error,None,best,"{'criterion': 'absolute_error', 'max_features'...",0.725057,0.607284,0.714520,0.716763,0.761295,0.704984,0.051670,5
17,0.051771,0.003371,0.004998,0.000632,absolute_error,None,random,"{'criterion': 'absolute_error', 'max_features'...",0.700155,0.575668,0.703106,0.727258,0.729456,0.687128,0.057009,17
18,0.063562,0.004755,0.005598,0.001624,absolute_error,auto,best,"{'criterion': 'absolute_error', 'max_features'...",0.735910,0.652242,0.724060,0.724092,0.749264,0.717114,0.033741,1
19,0.048770,0.004306,0.004998,0.001096,absolute_error,auto,random,"{'criterion': 'absolute_error', 'max_features'...",0.719286,0.612926,0.683506,0.704682,0.710742,0.686228,0.038510,18
20,0.031779,0.003483,0.006198,0.000979,absolute_error,sqrt,best,"{'criterion': 'absolute_error', 'max_features'...",0.733723,0.602401,0.658197,0.648751,0.690132,0.666641,0.043749,26
21,0.026388,0.003004,0.006193,0.001601,absolute_error,sqrt,random,"{'criterion': 'absolute_error', 'max_features'...",0.681201,0.559233,0.776357,0.731413,0.768666,0.703374,0.079554,7
22,0.033978,0.002094,0.005596,0.001019,absolute_error,log2,best,"{'criterion': 'absolute_error', 'max_features'...",0.688817,0.600271,0.702845,0.717263,0.718955,0.685630,0.044054,21
23,0.025784,0.001469,0.004801,0.000745,absolute_error,log2,random,"{'criterion': 'absolute_error', 'max_features'...",0.642264,0.476142,0.686078,0.674963,0.725697,0.641029,0.086647,30
24,0.061766,0.003600,0.005599,0.000490,absolute_error,None,best,"{'criterion': 'absolute_error', 'max_features'...",0.724976,0.645582,0.723376,0.738423,0.741113,0.714694,0.035267,2
25,0.050171,0.002477,0.006196,0.002991,absolute_error,None,random,"{'criterion': 'absolute_error', 'max_features'...",0.666578,0.550670,0.755988,0.749347,0.737699,0.692056,0.077578,14
26,0.069564,0.005316,0.005395,0.000491,absolute_error,auto,best,"{'criterion': 'absolute_error', 'max_features'...",0.744485,0.553240,0.720683,0.717665,0.753268,0.697868,0.073583,11
27,0.046976,0.007316,0.005394,0.002241,absolute_error,auto,random,"{'criterion': 'absolute_error', 'max_features'...",0.721989,0.632415,0.777198,0.699469,0.698180,0.705850,0.046569,4
28,0.030185,0.002928,0.005195,0.000403,absolute_error,sqrt,best,"{'criterion': 'absolute_error', 'max_features'...",0.663758,0.622505,0.676518,0.763480,0.733742,0.692001,0.050435,15
29,0.028780,0.002923,0.005398,0.001199,absolute_error,sqrt,random,"{'criterion': 'absolute_error', 'max_features'...",0.720034,0.623359,0.696952,0.691187,0.733640,0.693034,0.038082,12
30,0.034182,0.003865,0.005594,0.000798,absolute_error,log2,best,"{'criterion': 'absolute_error', 'max_features'...",0.750117,0.601183,0.646913,0.692685,0.739211,0.686022,0.056052,19
31,0.026783,0.002040,0.004396,0.000491,absolute_error,log2,random,"{'criterion': 'absolute_error', 'max_features'...",0.745422,0.566636,0.716912,0.681204,0.586467,0.659328,0.070862,28

In [17]:
age_input=int(input("Enter age: "))
bmi_input=float(input("Enter bmi: "))
children_input=float(input("Enter children: "))
gender_male_input=int(input("Enter Gender: "))
gender_female_input=int(input("Enter Gender: "))
smoker_yes_input=int(input("Enter smoker: "))
smoker_no_input=int(input("Enter smoker: "))

Enter age: 20
Enter bmi: 34.5
Enter children: 2
Enter Gender: 1
Enter Gender: 0
Enter smoker: 1
Enter smoker: 0

In [18]:
future_predict=grid.predict([[age_input,bmi_input,children_input,gender_male_input,gender_female_input,smoker_yes_input,smoker_no_input]])
print("Future Prediction{}".format(future_predict))

Future Prediction[3579.8287]

C:\Users\Jayarajan\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(